version: '3'

services:
  php:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Use the custom Dockerfile
    container_name: openbiblio-php
    ports:
      - "4523:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    links:
        - mysql
    networks:
      - openBiblio

  mysql:
    image: mysql
    container_name: openbiblio-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # Map MySQL port if needed
    networks:
      - openBiblio
    volumes:
      - ./data/db:/var/lib/mysql
    command: --character-set-server=latin1 --collation-server=latin1_german1_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: openbiblio-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: openbiblio-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
        - "8085:80"
    networks:
      - openBiblio

networks:
  openBiblio:


