version: '3'

services:
  php:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile.php-xdebug  # Use the custom Dockerfile
    container_name: openbiblio-php
    ports:
      - "4523:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3307
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - openBiblio

  mysql:
    image: mysql
    container_name: openbiblio-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # Map MySQL port if needed
    networks:
      - openBiblio

networks:
  openBiblio:


